Update index.markdown elaborated on the high fees will solve spam
wtfhappenedinfeb2023/wtfhappenedinfeb2023.github.io pull request #23
Opened 2024-02-19 20:05 UTC by GregTonoski

2024-02-23 15:06 UTC, GregTonoski commented
Is there an issue that delays acceptance of the change, perhaps? @piratebiscuit , @Retropex

2024-02-23 15:52 UTC, piratebiscuit commented
Sorry @GregTonoski it took me longer than planned. I'd like to propose some adjustments. I tried doing a review and commit with the online tool offered by Github and it is a total failure for now now, still trying to understand what's actually happening.

2024-02-23 16:06 UTC, piratebiscuit requested changes
Please consider this review. Feel free to discuss any point proposed. Thanks!

2024-02-23 16:06 UTC, piratebiscuit commented on index.markdown
> +While it is true that spammers make short-lived attempts to profit, the history shows that they keep repeating them. Their payoff depends on collection of money from gullible or over-excited fools an
I propose changing "gullible or over-excited fools" everywhere by "high-time preference profit seeking actors".

2024-02-23 16:06 UTC, piratebiscuit commented on index.markdown
> +Bitcoin transaction fees impact on profit is negligable because they are small in comparison to amount of money collected from gullible or over-excited fools. Most probably spammers spend more on adv
Typo "narritive".

2024-02-23 16:06 UTC, piratebiscuit commented on index.markdown
> +In consequence of high fees Bitcoin is less decentralized. There are more and more coins (so-called unspendable or uneconomical UTXOs) with amount smaller than the spam-inflated fee to transact. Majo
Please detail your thought here: "In consequence of high fees Bitcoin is less decentralized."
Invert "coins" and "UTXOs". UTXO is the proper name, coins is the so-called name.
I would also propose to remove "take control over Bitcoin", controlling UTXOs does not give control over Bitcoin does it? Or please detail your thought.
"makes" -> "make"
Rephrase "seize control and keep it".

2024-02-23 16:30 UTC, GregTonoski commented on index.markdown
> +While it is true that spammers make short-lived attempts to profit, the history shows that they keep repeating them. Their payoff depends on collection of money from gullible or over-excited fools an
"High-time preference" and "profit seeking" sounds like typical phenomenon - foundation of homo oeconomicus in general. In such case, I would suggest deletion of the text "high-time preference profit seeking actors" because it doesn't add anything particular in my opinion.

"Gullible or over-excited fools" may hint at greater fool theory which fits in here.

2024-02-24 11:20 UTC, GregTonoski commented
New version pending review by @piratebiscuit.

2024-02-26 21:50 UTC, piratebiscuit commented on index.markdown
> +While it is true that spammers make short-lived attempts to profit, the history shows that they keep repeating them. Their payoff depends on collection of money from gullible or over-excited fools an
Alright, I understand your point, but fool is kind of an insult too... 
If the goal here is to convince, wouldn't it be better to try to explain things in a less agressive manner? Some do not know/understand they are being "fools", they just think it's how it works or are stuck in the FIAT rat race. You can propose some other vocabulary maybe? A less insulting lexicon would be prefered. Nowhere in the page do we try to insult or derogate the reader, this would be the only place.
https://www.espressoenglish.net/how-to-use-the-word-fool-in-english/#:~:text=Note%3A%20Calling%20someone%20a%20fool,good%20sense%20or%20good%20judgment.

2024-02-27 08:11 UTC, GregTonoski commented on index.markdown
> +While it is true that spammers make short-lived attempts to profit, the history shows that they keep repeating them. Their payoff depends on collection of money from gullible or over-excited fools an
I replaced "fools" with "people". Feel free to further replace with other words, e.g. victims if you like.

2024-02-27 13:50 UTC, merged

2024-02-27 13:50 UTC, piratebiscuit commented
Thank you for your contribution and considering the comments @GregTonoski, appreciate it 🙏